<a href="https://colab.research.google.com/github/Jose-Angel009/unidad1/blob/main/Practica%207.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Jose Angel Velazquez ortiz-Practica 7-25 de septiembre 2025.
-----------------------
Slicing NumpPy
-----------------------
Utilice STEP para determinar el paso de el corte:
Ejemplo:([1,2,3,4,5,6,7])-Devuelve todos los elementos del indice 1 al indice 5

In [1]:
import numpy as np
arreglo = np.array([1,2,3,4,5,6,7])
print(arreglo[1:5:2])

[2 4]


Ejemplo 2:([1,2,3,4,5,6,7])
Devuelve los elementos de la matriz


In [2]:
import numpy as np
arreglo = np.array([1,2,3,4,5,6,7])
print(arreglo[::2])

[1 3 5 7]


Sislice de matrices 2D
--------------------------
Ejemplo 3:([[1,2,3,4,5], [6,7,8,9,10]])
DEl segundo elemento,

In [10]:
import numpy as np
arreglo=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arreglo[1,1:4:])

[7 8 9]


Ejemplo 4: ([[1,2,3,4,5],[6,7,8,9,10]])
De ambos elementos devuelve el incice 2
-------------------------


In [13]:
import numpy as np
arreglo=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arreglo[0:2,2])

[3 8]


Ejemplo 5:([[1,2,3,4,5], [6,7,8,9,10]])
DE ambos elementos corta el indice 1 al indice 4

In [15]:
import numpy as np
arreglo=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arreglo[0:4,1:4])

[[2 3 4]
 [7 8 9]]


Ejemplo 1- Autonomo
Del siguiente arreglo,¿cual es el resultado?
([1,2,3,4,5,6,7,])
Corta del 1er elemento al 3er elemento con paso 2

In [22]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[0:6:2])

[1 3 5]
