<a href="https://colab.research.google.com/github/Jose-Angel009/unidad1/blob/main/Practica%206.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Jose Angel Velazuez ortiz - 24 de septiembre de 2025
Practica 6 - Cortar Arreglos NumPy
----------------------------------
Slice en Python significa tomar elementos de un indice determinado indice.

Pasamos Slice en lugar del indice de esta manera:[stard:end]
Sino pasamos el inicio se concidera 0
Sino pasamos el final su longitud es concideradauna matriz de unadimencio
----------------
Ejemplo:([1,2,3,4,5,6,7])
Cortar los elementos del indice 1 al indice 5      
---------


In [2]:
import numpy as np

arreglo=np.array([1,2,3,4,5,6,7])

print(arreglo[1:5])

[2 3 4 5]


Ejemplo 2:
([1,2,3,4,5,6,7])
cortar del indice 4 hasta el final de la matriz
-----------------------

In [8]:
import numpy as np

arreglo=np.array([1,2,3,4,5,6,7])

print(arreglo[4:])

[5 6 7]


Ejemplo 3
([1,2,3,4,5,6,7])
Cortar elementos desde el principio hasta el indice 5

In [17]:
import numpy as np

arreglo=np.array([1,2,3,4,5,6,7])

print(arreglo[:5])

[1 2 3 4 5]


Ejemplo 4

([1,2,3,4,5,6,7])
Corte negativo.Untilizamos el operador "menos" para hacer referencia a un indice desde el final
------------------------
Cortar desde el indice 3 hasta el final al indice 1desde el final

In [20]:
import numpy as np

arreglo=np.array([1,2,3,4,5,6,7])

print(arreglo[-3:-1])

[5 6]
